In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv("data.csv")

In [3]:
data.head()

Suburb           Address  Rooms Type      Price Method SellerG  \
0  Abbotsford      85 Turner St      2    h  1480000.0      S  Biggin   
1  Abbotsford   25 Bloomburg St      2    h  1035000.0      S  Biggin   
2  Abbotsford      5 Charles St      3    h  1465000.0     SP  Biggin   
3  Abbotsford  40 Federation La      3    h   850000.0     PI  Biggin   
4  Abbotsford       55a Park St      4    h  1600000.0     VB  Nelson   

        Date  Distance  Postcode  ...  Bathroom  Car  Landsize  BuildingArea  \
0  3/12/2016       2.5    3067.0  ...       1.0  1.0     202.0           NaN   
1  4/02/2016       2.5    3067.0  ...       1.0  0.0     156.0          79.0   
2  4/03/2017       2.5    3067.0  ...       2.0  0.0     134.0         150.0   
3  4/03/2017       2.5    3067.0  ...       2.0  1.0      94.0           NaN   
4  4/06/2016       2.5    3067.0  ...       1.0  2.0     120.0         142.0   

   YearBuilt  CouncilArea Lattitude  Longtitude             Regionname  \
0        NaN        Yarra  -37.7996    144.9984  Northern Metropolitan   
1     1900.0        Yarra  -37.8079    144.9934  Northern Metropolitan   
2     1900.0        Yarra  -37.8093    144.9944  Northern Metropolitan   
3        NaN        Yarra  -37.7969    144.9969  Northern Metropolitan   
4     2014.0        Yarra  -37.8072    144.9941  Northern Metropolitan   

  Propertycount  
0        4019.0  
1        4019.0  
2        4019.0  
3        4019.0  
4        4019.0  

[5 rows x 21 columns]

In [4]:
data.isnull()

Suburb  Address  Rooms   Type  Price  Method  SellerG   Date  Distance  \
0       False    False  False  False  False   False    False  False     False   
1       False    False  False  False  False   False    False  False     False   
2       False    False  False  False  False   False    False  False     False   
3       False    False  False  False  False   False    False  False     False   
4       False    False  False  False  False   False    False  False     False   
...       ...      ...    ...    ...    ...     ...      ...    ...       ...   
13575   False    False  False  False  False   False    False  False     False   
13576   False    False  False  False  False   False    False  False     False   
13577   False    False  False  False  False   False    False  False     False   
13578   False    False  False  False  False   False    False  False     False   
13579   False    False  False  False  False   False    False  False     False   

       Postcode  ...  Bathroom    Car  Landsize  BuildingArea  YearBuilt  \
0         False  ...     False  False     False          True       True   
1         False  ...     False  False     False         False      False   
2         False  ...     False  False     False         False      False   
3         False  ...     False  False     False          True       True   
4         False  ...     False  False     False         False      False   
...         ...  ...       ...    ...       ...           ...        ...   
13575     False  ...     False  False     False          True      False   
13576     False  ...     False  False     False         False      False   
13577     False  ...     False  False     False          True      False   
13578     False  ...     False  False     False         False      False   
13579     False  ...     False  False     False         False      False   

       CouncilArea  Lattitude  Longtitude  Regionname  Propertycount  
0            False      False       False       False          False  
1            False      False       False       False          False  
2            False      False       False       False          False  
3            False      False       False       False          False  
4            False      False       False       False          False  
...            ...        ...         ...         ...            ...  
13575         True      False       False       False          False  
13576         True      False       False       False          False  
13577         True      False       False       False          False  
13578         True      False       False       False          False  
13579         True      False       False       False          False  

[13580 rows x 21 columns]

In [5]:
data.isnull().sum()

Suburb              0
Address             0
Rooms               0
Type                0
Price               0
Method              0
SellerG             0
Date                0
Distance            0
Postcode            0
Bedroom2            0
Bathroom            0
Car                62
Landsize            0
BuildingArea     6450
YearBuilt        5375
CouncilArea      1369
Lattitude           0
Longtitude          0
Regionname          0
Propertycount       0
dtype: int64

In [6]:
data['Car'].fillna(data['Car'].mean(),inplace=True)

In [7]:
data.isnull().sum()

Suburb              0
Address             0
Rooms               0
Type                0
Price               0
Method              0
SellerG             0
Date                0
Distance            0
Postcode            0
Bedroom2            0
Bathroom            0
Car                 0
Landsize            0
BuildingArea     6450
YearBuilt        5375
CouncilArea      1369
Lattitude           0
Longtitude          0
Regionname          0
Propertycount       0
dtype: int64

In [15]:
data['BuildingArea'].fillna(data['BuildingArea'].mean(),inplace=True)
data['YearBuilt'].fillna(data['YearBuilt'].mean(),inplace=True)

In [16]:
data.isnull().sum()

Suburb           0
Address          0
Rooms            0
Type             0
Price            0
Method           0
SellerG          0
Date             0
Distance         0
Postcode         0
Bedroom2         0
Bathroom         0
Car              0
Landsize         0
BuildingArea     0
YearBuilt        0
CouncilArea      0
Lattitude        0
Longtitude       0
Regionname       0
Propertycount    0
dtype: int64

In [17]:
data.dtypes

Suburb            object
Address           object
Rooms              int64
Type              object
Price            float64
Method            object
SellerG           object
Date              object
Distance         float64
Postcode         float64
Bedroom2         float64
Bathroom         float64
Car              float64
Landsize         float64
BuildingArea     float64
YearBuilt        float64
CouncilArea       object
Lattitude        float64
Longtitude       float64
Regionname        object
Propertycount    float64
dtype: object

In [18]:
data['CouncilArea'].fillna(data['CouncilArea'].mode()[0],inplace=True)

In [19]:
data.isnull().sum()

Suburb           0
Address          0
Rooms            0
Type             0
Price            0
Method           0
SellerG          0
Date             0
Distance         0
Postcode         0
Bedroom2         0
Bathroom         0
Car              0
Landsize         0
BuildingArea     0
YearBuilt        0
CouncilArea      0
Lattitude        0
Longtitude       0
Regionname       0
Propertycount    0
dtype: int64

In [20]:
data.dtypes

Suburb            object
Address           object
Rooms              int64
Type              object
Price            float64
Method            object
SellerG           object
Date              object
Distance         float64
Postcode         float64
Bedroom2         float64
Bathroom         float64
Car              float64
Landsize         float64
BuildingArea     float64
YearBuilt        float64
CouncilArea       object
Lattitude        float64
Longtitude       float64
Regionname        object
Propertycount    float64
dtype: object

In [24]:
data['Car']=data['Car'].astype('int')

In [25]:
data.dtypes

Suburb            object
Address           object
Rooms              int64
Type              object
Price            float64
Method            object
SellerG           object
Date              object
Distance         float64
Postcode         float64
Bedroom2         float64
Bathroom         float64
Car                int32
Landsize         float64
BuildingArea     float64
YearBuilt        float64
CouncilArea       object
Lattitude        float64
Longtitude       float64
Regionname        object
Propertycount    float64
dtype: object

In [29]:
data['Postcode'] = data['Postcode'].astype('int64')
data['Bedroom2'] = data['Bedroom2'].astype('int64')
data['Bathroom'] = data['Bathroom'].astype('int64')
data['Car'] = data['Car'].astype('int64')
data['YearBuilt'] = data['YearBuilt'].astype('int64')

In [30]:
data.dtypes

Suburb            object
Address           object
Rooms              int64
Type              object
Price            float64
Method            object
SellerG           object
Date              object
Distance         float64
Postcode           int64
Bedroom2           int64
Bathroom           int64
Car                int64
Landsize         float64
BuildingArea     float64
YearBuilt          int64
CouncilArea       object
Lattitude        float64
Longtitude       float64
Regionname        object
Propertycount    float64
dtype: object

In [31]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
data['Suburb']=le.fit_transform(data['Suburb'])
data

Suburb           Address  Rooms Type      Price Method   SellerG  \
0           0      85 Turner St      2    h  1480000.0      S    Biggin   
1           0   25 Bloomburg St      2    h  1035000.0      S    Biggin   
2           0      5 Charles St      3    h  1465000.0     SP    Biggin   
3           0  40 Federation La      3    h   850000.0     PI    Biggin   
4           0       55a Park St      4    h  1600000.0     VB    Nelson   
...       ...               ...    ...  ...        ...    ...       ...   
13575     302      12 Strada Cr      4    h  1245000.0      S     Barry   
13576     305     77 Merrett Dr      3    h  1031000.0     SP  Williams   
13577     305       83 Power St      3    h  1170000.0      S     Raine   
13578     305      96 Verdon St      4    h  2500000.0     PI   Sweeney   
13579     313        6 Agnes St      4    h  1285000.0     SP   Village   

             Date  Distance  Postcode  ...  Bathroom  Car  Landsize  \
0       3/12/2016       2.5      3067  ...         1    1     202.0   
1       4/02/2016       2.5      3067  ...         1    0     156.0   
2       4/03/2017       2.5      3067  ...         2    0     134.0   
3       4/03/2017       2.5      3067  ...         2    1      94.0   
4       4/06/2016       2.5      3067  ...         1    2     120.0   
...           ...       ...       ...  ...       ...  ...       ...   
13575  26/08/2017      16.7      3150  ...         2    2     652.0   
13576  26/08/2017       6.8      3016  ...         2    2     333.0   
13577  26/08/2017       6.8      3016  ...         2    4     436.0   
13578  26/08/2017       6.8      3016  ...         1    5     866.0   
13579  26/08/2017       6.3      3013  ...         1    1     362.0   

       BuildingArea  YearBuilt  CouncilArea Lattitude  Longtitude  \
0         151.96765       1964        Yarra -37.79960   144.99840   
1          79.00000       1900        Yarra -37.80790   144.99340   
2         150.00000       1900        Yarra -37.80930   144.99440   
3         151.96765       1964        Yarra -37.79690   144.99690   
4         142.00000       2014        Yarra -37.80720   144.99410   
...             ...        ...          ...       ...         ...   
13575     151.96765       1981     Moreland -37.90562   145.16761   
13576     133.00000       1995     Moreland -37.85927   144.87904   
13577     151.96765       1997     Moreland -37.85274   144.88738   
13578     157.00000       1920     Moreland -37.85908   144.89299   
13579     112.00000       1920     Moreland -37.81188   144.88449   

                       Regionname Propertycount  
0           Northern Metropolitan        4019.0  
1           Northern Metropolitan        4019.0  
2           Northern Metropolitan        4019.0  
3           Northern Metropolitan        4019.0  
4           Northern Metropolitan        4019.0  
...                           ...           ...  
13575  South-Eastern Metropolitan        7392.0  
13576        Western Metropolitan        6380.0  
13577        Western Metropolitan        6380.0  
13578        Western Metropolitan        6380.0  
13579        Western Metropolitan        6543.0  

[13580 rows x 21 columns]

In [32]:
data['CouncilArea'].unique()

array(['Yarra', 'Moonee Valley', 'Port Phillip', 'Darebin', 'Hobsons Bay',
       'Stonnington', 'Boroondara', 'Monash', 'Glen Eira', 'Whitehorse',
       'Maribyrnong', 'Bayside', 'Moreland', 'Manningham', 'Banyule',
       'Melbourne', 'Kingston', 'Brimbank', 'Hume', 'Knox', 'Maroondah',
       'Casey', 'Melton', 'Greater Dandenong', 'Nillumbik', 'Whittlesea',
       'Frankston', 'Macedon Ranges', 'Yarra Ranges', 'Wyndham',
       'Cardinia', 'Unavailable', 'Moorabool'], dtype=object)

In [34]:
data['CouncilArea']=le.fit_transform(data['CouncilArea'])

In [35]:
data

Suburb           Address  Rooms Type      Price Method   SellerG  \
0           0      85 Turner St      2    h  1480000.0      S    Biggin   
1           0   25 Bloomburg St      2    h  1035000.0      S    Biggin   
2           0      5 Charles St      3    h  1465000.0     SP    Biggin   
3           0  40 Federation La      3    h   850000.0     PI    Biggin   
4           0       55a Park St      4    h  1600000.0     VB    Nelson   
...       ...               ...    ...  ...        ...    ...       ...   
13575     302      12 Strada Cr      4    h  1245000.0      S     Barry   
13576     305     77 Merrett Dr      3    h  1031000.0     SP  Williams   
13577     305       83 Power St      3    h  1170000.0      S     Raine   
13578     305      96 Verdon St      4    h  2500000.0     PI   Sweeney   
13579     313        6 Agnes St      4    h  1285000.0     SP   Village   

             Date  Distance  Postcode  ...  Bathroom  Car  Landsize  \
0       3/12/2016       2.5      3067  ...         1    1     202.0   
1       4/02/2016       2.5      3067  ...         1    0     156.0   
2       4/03/2017       2.5      3067  ...         2    0     134.0   
3       4/03/2017       2.5      3067  ...         2    1      94.0   
4       4/06/2016       2.5      3067  ...         1    2     120.0   
...           ...       ...       ...  ...       ...  ...       ...   
13575  26/08/2017      16.7      3150  ...         2    2     652.0   
13576  26/08/2017       6.8      3016  ...         2    2     333.0   
13577  26/08/2017       6.8      3016  ...         2    4     436.0   
13578  26/08/2017       6.8      3016  ...         1    5     866.0   
13579  26/08/2017       6.3      3013  ...         1    1     362.0   

       BuildingArea  YearBuilt  CouncilArea  Lattitude  Longtitude  \
0         151.96765       1964           31  -37.79960   144.99840   
1          79.00000       1900           31  -37.80790   144.99340   
2         150.00000       1900           31  -37.80930   144.99440   
3         151.96765       1964           31  -37.79690   144.99690   
4         142.00000       2014           31  -37.80720   144.99410   
...             ...        ...          ...        ...         ...   
13575     151.96765       1981           23  -37.90562   145.16761   
13576     133.00000       1995           23  -37.85927   144.87904   
13577     151.96765       1997           23  -37.85274   144.88738   
13578     157.00000       1920           23  -37.85908   144.89299   
13579     112.00000       1920           23  -37.81188   144.88449   

                       Regionname Propertycount  
0           Northern Metropolitan        4019.0  
1           Northern Metropolitan        4019.0  
2           Northern Metropolitan        4019.0  
3           Northern Metropolitan        4019.0  
4           Northern Metropolitan        4019.0  
...                           ...           ...  
13575  South-Eastern Metropolitan        7392.0  
13576        Western Metropolitan        6380.0  
13577        Western Metropolitan        6380.0  
13578        Western Metropolitan        6380.0  
13579        Western Metropolitan        6543.0  

[13580 rows x 21 columns]

In [41]:
data=pd.get_dummies(data,columns=['Distance'])

In [42]:
data

Suburb           Address  Rooms Type      Price   SellerG        Date  \
0           0      85 Turner St      2    h  1480000.0    Biggin   3/12/2016   
1           0   25 Bloomburg St      2    h  1035000.0    Biggin   4/02/2016   
2           0      5 Charles St      3    h  1465000.0    Biggin   4/03/2017   
3           0  40 Federation La      3    h   850000.0    Biggin   4/03/2017   
4           0       55a Park St      4    h  1600000.0    Nelson   4/06/2016   
...       ...               ...    ...  ...        ...       ...         ...   
13575     302      12 Strada Cr      4    h  1245000.0     Barry  26/08/2017   
13576     305     77 Merrett Dr      3    h  1031000.0  Williams  26/08/2017   
13577     305       83 Power St      3    h  1170000.0     Raine  26/08/2017   
13578     305      96 Verdon St      4    h  2500000.0   Sweeney  26/08/2017   
13579     313        6 Agnes St      4    h  1285000.0   Village  26/08/2017   

       Postcode  Bedroom2  Bathroom  ...  Distance_39.0  Distance_39.8  \
0          3067         2         1  ...          False          False   
1          3067         2         1  ...          False          False   
2          3067         3         2  ...          False          False   
3          3067         3         2  ...          False          False   
4          3067         3         1  ...          False          False   
...         ...       ...       ...  ...            ...            ...   
13575      3150         4         2  ...          False          False   
13576      3016         3         2  ...          False          False   
13577      3016         3         2  ...          False          False   
13578      3016         4         1  ...          False          False   
13579      3013         4         1  ...          False          False   

       Distance_41.0  Distance_43.3  Distance_44.2  Distance_45.2  \
0              False          False          False          False   
1              False          False          False          False   
2              False          False          False          False   
3              False          False          False          False   
4              False          False          False          False   
...              ...            ...            ...            ...   
13575          False          False          False          False   
13576          False          False          False          False   
13577          False          False          False          False   
13578          False          False          False          False   
13579          False          False          False          False   

       Distance_45.9 Distance_47.3  Distance_47.4  Distance_48.1  
0              False         False          False          False  
1              False         False          False          False  
2              False         False          False          False  
3              False         False          False          False  
4              False         False          False          False  
...              ...           ...            ...            ...  
13575          False         False          False          False  
13576          False         False          False          False  
13577          False         False          False          False  
13578          False         False          False          False  
13579          False         False          False          False  

[13580 rows x 225 columns]

In [43]:
from sklearn.preprocessing import OneHotEncoder
v=OneHotEncoder(sparse=False)
v.fit(data)
v2=v.transform(data)
print(v2)

C:\Users\neils\AppData\Roaming\Python\Python312\site-packages\sklearn\preprocessing\_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


[[1. 0. 0. ... 0. 1. 0.]
 [1. 0. 0. ... 0. 1. 0.]
 [1. 0. 0. ... 0. 1. 0.]
 ...
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]]


In [44]:
s=data['SellerG']
s1=pd.get_dummies(s,prefix="SELLERG")
s=pd.concat([s,s1],axis=1)


In [45]:
print(s)

        SellerG  SELLERG_@Realty  SELLERG_ASL  SELLERG_Abercromby's  \
0        Biggin            False        False                 False   
1        Biggin            False        False                 False   
2        Biggin            False        False                 False   
3        Biggin            False        False                 False   
4        Nelson            False        False                 False   
...         ...              ...          ...                   ...   
13575     Barry            False        False                 False   
13576  Williams            False        False                 False   
13577     Raine            False        False                 False   
13578   Sweeney            False        False                 False   
13579   Village            False        False                 False   

       SELLERG_Ace  SELLERG_Alexkarbon  SELLERG_Allens  SELLERG_Anderson  \
0            False               False           False             Fals